### ISSUE TITLE
Retrying sender doesn't retry enough

### ISSUE THREAD

**Issue by alexpogue** [felix-hilden/tekore#255]
Heyo, another thing to report on my usage of Tekore's RetryingSender.

I occasionally get an `httpx.ConnectError [Errno 101] Network is unreachable` or other 4xx HTTP return codes. In my case, I would like Tekore to retry a few times when this happens, and in my setup, retrying seems to work - potentially my VMs have a flaky network, etc.

I hesitate to report this issue because I understand why you wrote the code the way you did - 4xx errors are for user errors, 5xx are for server errors, so only catching and retrying on 5xx would make sense. However I saw many 4xx errors and "Network is unreachable" exceptions where the issue is resolved upon retry.

Full stack trace:
```
[2021-05-02 08:29:00,167: ERROR/ForkPoolWorker-2] Task playlist_search.routes.admin.reset_db_task[e19a272e-d0a6-4de8-8881-57a23d2caec5] raised unexpected: ConnectError('[Errno 101] Network is unreachable')
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bandbldr/git/playlist_search/playlist_search/routes/admin.py", line 70, in reset_db_task
    store_playlist_and_subobjects_to_db(user_spotify_id, playlist_spotify_id, spotify)
  File "/home/bandbldr/git/playlist_search/playlist_search/routes/admin.py", line 154, in store_playlist_and_subobjects_to_db
    playlist_snapshot_id  = lookup_playlist(playlist_spotify_id, fields=['snapshot_id'])['snapshot_id']
  File "/home/bandbldr/git/playlist_search/playlist_search/routes/util.py", line 73, in lookup_playlist
    api_playlist = spotify.playlist(playlist_spotify_id, fields=str_fields)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/tekore/_client/api/playlist/view.py", line 41, in wrapper
    return function(self, *args, **kwargs)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/tekore/_sender/client.py", line 78, in wrapper
    response = self.send(request)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/tekore/_client/base.py", line 117, in send
    return self.sender.send(request)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/tekore/_sender/extending.py", line 95, in send
    r = self.sender.send(request)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/tekore/_sender/concrete.py", line 41, in send
    data=request.data,
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/httpx/_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/httpx/_client.py", line 772, in send
    history=[],
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/httpx/_client.py", line 809, in _send_handling_auth
    history=history,
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.local/share/virtualenvs/playlist_search-nA2ynR0j/lib/python3.7/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [Errno 101] Network is unreachable
```

**Comment by alexpogue** [comment]
I created a `SuperRetryingSender` to retry more often. Code can probably be improved - lots of duplicated code from `RetryingSender` could be cleaned up.

```
class SuperRetryingSender(RetryingSender):
    def __init__(self, retries: int = 0, sender: Sender = None):
        super().__init__(retries, sender)

    def send(self, request: Request) -> Union[Response, Coroutine[None, None, Response]]:
        if self.is_async:
            return self._async_send(request)

        tries = self.retries + 1
        delay_seconds = 1

        while tries > 0:
            try:
                r = self.sender.send(request)
                if r.status_code == 429:
                    seconds = r.headers.get('Retry-After', 1)
                    time.sleep(int(seconds) + 1)
                elif r.status_code >= 400 and tries > 1:
                    tries -= 1
                    time.sleep(delay_seconds)
                    delay_seconds *= 2
                else:
                    return r
            except ConnectError:
                tries -= 1
                time.sleep(delay_seconds)
                delay_seconds *= 2

    async def _async_send(self, request: Request) -> Response:
        tries = self.retries + 1
        delay_seconds = 1

        while tries > 0:
            try:
                r = await self.sender.send(request)

                if r.status_code == 429:
                    seconds = r.headers.get('Retry-After', 1)
                    await asyncio.sleep(int(seconds) + 1)
                elif r.status_code >= 400 and tries > 1:
                    tries -= 1
                    await asyncio.sleep(delay_seconds)
                    delay_seconds *= 2
```

Again, feel free to close this issue without action if this is not the direction you want to take Tekore. I just identified an issue I was facing and am sharing my solution in case it is useful to you!

Thanks again for your great work!

**Comment by felix-hilden** [comment]
I think we've established that this and #254 are essentially the same, so I'll close this issue now!
