### ISSUE TITLE
ValueError: 'EP' is not a valid AlbumType raised when calling current_user_top_tracks()

### ISSUE THREAD

**Issue by janishahn** [felix-hilden/tekore#318]
### Issue
ValueError is raised when calling current_user_top_tracks.
When calling the aforementioned function, I get the ValueError 'EP' is not a valid AlbumType. From the traceback it seems like the issue is  a validation issue. It traces back to a pydantic function that raises a KeyError, I am using up-to-date versions of both pydantic (v2.6.2), pydantic_core (v2.16.3) and tekore (v5.3.0).
I am using tekore in an async telegram bot using the package python-telegram-bot, but the error raised + traceback does not seem to have anything to do with it being async, other function calls (such as genre getting for an artist) work fine.

```
ValueError: 'EP' is not a valid AlbumType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project\Lib\site-packages\telegram\ext\_application.py", line 1234, in process_update
    await coroutine
  File "E:\Project\Lib\site-packages\telegram\ext\_basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\mybot.py", line 62, in wrapped
    return await func(update, context, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\mybot.py", line 595, in send_spotify_stats
    stats = mylib.get_recent_spotify_stats(Spotify, selection, 10)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\mylib.py", line 554, in get_recent_spotify_stats
    "top_tracks": Spotify.current_user_top_tracks(limit=amount, time_range=time_range).items,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_sender\client.py", line 90, in wrapper
    return try_post_func(request, response, *params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_sender\client.py", line 71, in try_post_func
    return post_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_client\decor\__init__.py", line 22, in parse_response
    return post_func(response.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_client\process.py", line 29, in post_func
    return type_(**json) if json is not None else None
           ^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_model\serialise.py", line 48, in __init__
    super().__init__(**data)
  File "E:\Project\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "E:\Project\Lib\site-packages\tekore\_model\serialise.py", line 48, in __init__
    super().__init__(**data)
  File "E:\Project\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "E:\Project\Lib\site-packages\tekore\_model\serialise.py", line 48, in __init__
    super().__init__(**data)
  File "E:\Project\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "E:\Project\Lib\site-packages\pydantic\_internal\_std_types_schema.py", line 93, in to_enum
    enum_field = enum_type(__input_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 740, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1162, in __new__
    raise exc
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1139, in __new__
    result = cls._missing_(value)
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_model\serialise.py", line 37, in _missing_
    return cls[value.lower()]
           ~~~^^^^^^^^^^^^^^^
  File "E:\Project\Lib\site-packages\tekore\_model\serialise.py", line 25, in __getitem__
    return super().__getitem__(name.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 797, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'ep'
```

### Expected behavior
Top tracks returned

### Steps to reproduce
Call current_user_top_tracks() with arbitrary parameters.

Minimal working example:
```
import tekore as tk

# authentication
conf = tk.config_from_file('userdata/tekore.cfg', return_refresh=True)
user_token = tk.refresh_user_token(*conf[:2], conf[3])
spotify = tk.Spotify(user_token)

# request user's top tracks (with a song from an EP in there)
top_monthly_tracks = spotify.current_user_top_tracks()
```

**Comment by felix-hilden** [comment]
Thanks for submitting the issue! The linked PR has a good fix and I'll probably release it later today with #317

**Comment by janishahn** [comment]
Alright thanks, I'll check it out!

**Comment by felix-hilden** [comment]
It's been released now, let me know if there are still issues!
